### ISSUE TITLE
sampleData not included

### ISSUE THREAD

**Issue by rudenoise** [thebeebs/WinJS-ListView-with-Different-Size-Items#1]
Hi,

I got this example via Gemma Yussuf and am only just coming around to using it. I'm piecing the data together manually but thought you might be able to post the data quicker?

Any help much appreciated.

Joel

**Comment by rudenoise** [comment]
Added pull request to fix https://github.com/thebeebs/WinJS-ListView-with-Different-Size-Items/pull/2

**Comment by thebeebs** [comment]
Thanks Joel, hope it helped solve your issue.

**Comment by thebeebs** [comment]
I must have missed the sampledata.js file when I committed this. Sorry about that. Glad to see you got it working.
